[connectors]
    [connectors.database]
    url = "sqlite:///./test.db"
    
    [connectors.llm_service]
    model = "gpt-3.5-turbo"
    
    [connectors.serverless_service]
    endpoint = "https://api.example.com/endpoint"

    # Add optional custom connector configurations here
    #[connectors.mycustomconnector]
    #custom_setting = "value"
